spring:
      profiles: peer1
      application:
        name: spring-cloud-consumer
server:
  port: 9001

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8000/eureka/
    server:
        waitTimeInMsWhenSyncEmpty: 0







