server:
  port: 8001

#===========spring security config start =============

spring:
  application:
        name: spring-cloud-eureka

#===========spring security config end =============

#===========eureka config start =============
eureka:
  instance:
    hostname: peer1
  client:
    #表示是否将自己注册到Eureka Server，默认为true。双注册中心设置为true
    register-with-eureka: true
    #表示是否从Eureka Server获取注册信息，默认为true。双注册中心设置为true
    fetch-registry: true
    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。
    # 默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
    serviceUrl:
#      defaultZone: http://${USER}:${PASSWORD}@peer1:8001/eureka/,http://${USER}:${PASSWORD}@peer3:8003/eureka/
      defaultZone: http://peer2:8002/eureka,http://peer3:8003/eureka

#===========eureka config end  =============





