
---
spring:
      profiles: peer1
      application:
        name: spring-cloud-eureka
      security:
        user:
          name: admin
          password: admin
server:
  port: 8001

#===========eureka config start =============
eureka:
  instance:
    hostname: peer1
  client:
    #表示是否将自己注册到Eureka Server，默认为true。双注册中心设置为true
    register-with-eureka: true
    #表示是否从Eureka Server获取注册信息，默认为true。双注册中心设置为true
    fetch-registry: true
    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。
    # 默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@peer2:8002/eureka/

#===========eureka config end  =============



---
spring:
      profiles: peer2
      application:
        name: spring-cloud-eureka
      security:
        user:
          name: admin
          password: admin
server:
  port: 8002

#===========eureka config start =============
eureka:
  instance:
    hostname: peer2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@peer1:8001/eureka/

#===========eureka config end  =============






